steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "${_DOCKERHUB_PASSWORD}" | docker login -u "${_DOCKERHUB_USERNAME}" --password-stdin'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'aritapan/sit323-webapp:latest'
      - '-t'
      - 'aritapan/sit323-webapp:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'aritapan/sit323-webapp']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'aritapan/sit323-webapp:latest'
      - 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/sit323-webapp/webapp:latest'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/sit323-webapp/webapp:latest'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/webapp-deployment'
      - 'webapp=aritapan/sit323-webapp:latest'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=australia-southeast1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=sit323-webapp'

substitutions:
  _DOCKERHUB_USERNAME: aritapan
  _DOCKERHUB_PASSWORD: '112233456'

options:
  logging: NONE
