apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: australia-southeast1-docker.pkg.dev/sit323-26t1-kitayaso-309b8b4/sit323-webapp/webapp:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: persistent-data
              mountPath: /usr/share/nginx/data
      volumes:
        - name: persistent-data
          persistentVolumeClaim:
            claimName: webapp-pvc
